on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: | 
        echo "::set-output name=date::$(date +%s000)"
    - name: Integrate with Upwind - GET Auth & Post Event
      run: |
        auth_response=$(curl -s "https://auth.upwind.io/oauth/token" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=client_credentials" \
          --data-urlencode "audience=https://api.upwind.io" \
          --data-urlencode "client_id=${{ secrets.UPWIND_CLIENT_ID }}" \
          --data-urlencode "client_secret=${{ secrets.UPWIND_CLIENT_SECRET }}" || exit 0)
             
        ACCESS_TOKEN=$(echo "$auth_response" | jq -r '.access_token')
        
        response=$(curl -s "https://api.upwind.io/v1/organizations/${{ secrets.UPWIND_ORGANIZATION_ID }}/events" \
                 --write-out "\n%{http_code}" \
                 --request POST \
                 --header "Content-Type: application/json" \
                 --header "Authorization: Bearer $ACCESS_TOKEN" \
                 --data '{
                    "type": "image_build",
                    "reporter": "github_actions",
                    "data" :{
                      "image" : "nginx:latest",
                      "commit_sha" : "${{ github.sha }}",
                      "repository": "https://github.com/talbh-upwind/ci-test",
                      "branch": "main",
                      "image_sha": "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
                      "build_time" : "${{ steps.date.outputs.date }}"
                    }
                  }'
               )
        
        response_code=$(echo "$response" | tail -n 1)
                response_body=$(echo "$response" | sed '$d')
                if [ "$response_code" -eq 201 ]; then
                  echo "Successfully sent event to Upwind"
                fi
                echo "$response_body" | jq .
                exit 0
      env:
        IMAGE_SHA: ${{ needs.deploy.outputs.image_digest }}
        UPWIND_ORGANIZATION_ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}
        UPWIND_CLIENT_SECRET: ${{ secrets.UPWIND_CLIENT_SECRET }}
        UPWIND_CLIENT_ID: ${{ secrets.UPWIND_CLIENT_ID }}
